applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from . import views



urlpatterns = [
     path(
        'departamento-lista/',
         views.DepartamentoListView.as_view(),
         name='departamento-list'),


 ]

applications/home/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('prueba/', views.PruebaView.as_view()),
    path('add/', views.PruebaCreateView.as_view(), name='prueba_add'),
    path('resumen-foundation/',
        views.ResumenFoundationView.as_view(), 
        name='resumen'),
]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name="persona_app"

urlpatterns = [
     path(
        '',
         views.InicioView.as_view(),
         name='inicio'),
    path('prueba-todo-empleados',
          views.ListAllEmpleado.as_view(),
          name='listar-todo'),

    path('buscar-empleado/',
            views.ListEmpleadosByKword.as_view(),
            name='lista-kword'
     ),


    path('lista-area/<shorname>/',
        views.ListByAreEmpleados.as_view(),
        name='empleados_area'),

    path('lista-empleados-admin/',
        views.ListEmpleadosAdmin.as_view(),
        name='lista-admin'),

    path('ver-empleados/<pk>/', 
            views.EmpleadoDetailView.as_view(),
            name='empleado_detail'),

    path('update-empleados/<pk>/', 
            views.EmpleadoUpdateView.as_view(),
            name='modificar_empleado'),

    path('add-empleado/',
            views.EmpleadoCreateView.as_view(),
            name='empleado-add'),
    path(
        'success/',
         views.succesview.as_view(),
         name='correcto'),

    path(
        'delete-empleado/<pk>/',
         views.EmpleadoDeleteView.as_view(),
         name='eliminar-empleado'),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.persona.urls')),
    path('', include('applications.departamento.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models
from django.forms import BooleanField

# Create your models here.
class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50)
    shor_name = models.CharField('Nombre Corto', max_length=20)
    anulate = models.BooleanField('Anulado',default=False)
    

    def __str__(self):
        return str(self.id) + '-' +self.name+ '-'+ self.shor_name

applications/home/models.py
from django.db import models

# Create your models here.
class Prueba(models.Model):
    titulo =models.CharField(max_length=100)
    subtitulo = models.CharField(max_length=50)
    cantidad = models.IntegerField()

    def __str__(self):
        return self.titulo+'-'+ self.subtitulo

applications/persona/models.py
from os import F_OK
from django.db import models
from applications.departamento.models import Departamento

# Create your models here.
class Empleado(models.Model):
    JOB_CHOICES = (
        ('0','CONTADOR'),
        ('1','ADMINISTRADOR'),
        ('2','ECONOMISTA'),
        ('3','OTROS'),
    )
    first_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('apellidos', max_length=60)
    job =models.CharField('trabajo',max_length=50,choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento,on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado', blank=True, null=True)
 
    def __str__(self):
        return str(self.id)+ '-'+ self.first_name+ '-' + self.last_name

applications/home/forms.py
from tkinter import Widget
from django import forms 
from  .models import Prueba

class PruebaForm(forms.ModelForm):

    class Meta:
        model = Prueba
        fields =(
            'titulo',
            'subtitulo',
            'cantidad',
        )
        Widgets ={
            'titulo':forms.TextInput(
                attrs ={
                    'placeholder':'ingrese texto aqui',
                }
            )


        }

    def clean_cantidad(self):
        cantidad =self.cleaned_data['cantidad']
        if cantidad < 10:
            raise forms.ValidationError('Ingrese el erro mayor a 10')
        return cantidad

applications/departamento/views.py
from multiprocessing import context
from re import template
from django.shortcuts import render

from .models import Departamento

from django.views.generic import(
    ListView,
    DetailView,
    CreateView,
    TemplateView

) 
# Create your views here.

class DepartamentoListView(ListView):
    template_name = "departamento/lista.html"
    model = Departamento
    context_object_name= 'departamentos'

applications/home/views.py
from re import template
from django.shortcuts import render

from .models import Prueba

from . forms import PruebaForm

# Create your views here.
from django.views.generic import TemplateView,CreateView

class PruebaView(TemplateView):
    template_name = 'home/prueba.html'


class PruebaCreateView(CreateView):
    template_name = "home/add.html"
    model = Prueba
    form_class = PruebaForm
    success_url ='.'

class ResumenFoundationView(TemplateView):
    template_name = 'home/resumen_foundation.html'

applications/persona/views.py
from dataclasses import fields
from multiprocessing import context
from pipes import Template
from re import template
from django.shortcuts import render
from django.urls import reverse_lazy

# Create your views here.

from django.views.generic import(
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView

) 

from .models import Empleado

class ListAllEmpleado(ListView):
    template_name ='persona/list_all.html'
    paginate_by=4
    model =Empleado
    context_object_name = 'empleados'

    def get_queryset(self):
        print('***************')
        palabra_clave = self.request.GET.get("kword",'')
        lista = Empleado.objects.filter(
            first_name__icontains=palabra_clave
        )
        return lista


class ListEmpleadosAdmin(ListView):
    template_name ='persona/list_empleados.html'
    paginate_by=10
    ordering ='first_name'
    model =Empleado
    context_object_name = 'empleados'

  


class ListByAreEmpleados(ListView):
    """lista de empleados de una Area"""
    template_name = "persona/list_by_area.html"
    context_object_name= 'empleados'
 
    def get_queryset(self):
        #el codigo que yo quiero
        area = self.kwargs['shorname']
        lista = Empleado.objects.filter(
            departamento__shor_name=area
        )
        return lista




class EmpleadoCreateView(CreateView):
    template_name = "persona/add-empleado.html"
    model = Empleado
    fields = ('__all__')
    success_url = reverse_lazy('persona_app:lista-admin')


class succesview(TemplateView):
    template_name = "persona/success.html"


class InicioView(TemplateView):
    """Vista que carga la pagina de inicio"""
    template_name = 'inicio.html'

class ListEmpleadosByKword(ListView):
    template_name ='persona/by_kword.html'
    context_object_name ='hola'

    def get_queryset(self):
        print('***************')
        palabra_clave = self.request.GET.get("kword",'')
        lista = Empleado.objects.filter(
            first_name=palabra_clave
        )
        return lista

class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "persona/detail_empleado.html"

    def get_context_data(self,**kwargs):
        context = super(EmpleadoDetailView,self).get_context_data(**kwargs)
        context['titulo']='Empleado del mes'
        return context


class EmpleadoUpdateView(UpdateView):
    template_name = "persona/update.html"
    model =Empleado

    fields =[
        'first_name',
        'last_name',
        'job',
        'departamento',
        
    ]

    success_url = reverse_lazy('persona_app:lista-admin')

class EmpleadoDeleteView(DeleteView):
    template_name = "persona/delete.html"
    model =Empleado
    success_url = reverse_lazy('persona_app:lista-admin')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/foundation.min.css'%}">
    <title>{% block  titulo %}  {% endblock titulo  %}</title>
</head>
<body>
    {% block contenido%} {% endblock contenido %}


    <script src="{% static 'js/vendor/jquery.js' %}"></script>
    <script src="{% static 'js/vendor/what-input.js' %}"></script>
    <script src="{% static 'js/vendor/foundation.min.js' %}"></script>
    <script>
      $(document).foundation();
    </script>
</body>
</html>

templates/departamento/lista.html
{% extends 'base.html'%}

{% block titulo %}
listar departamentos
{% endblock titulo%}

{% block contenido %}
    {% include "includes/header.html"%}

    <div class ="grid-contaniner">
        <div class ="grid-x">
            <h1>departamentos en django</h1>
            <div class ="cell">
                <table>
                    <tbody>

                        {% for departamento in departamentos %}
                        <tr>
                            <td>{{departamento.name}}</td>
                            <td>{{departamento.shor_name}}</td>
                            <td>
                                <a class="button warning" href="{% url 'persona_app:empleados_area' departamento.shor_name %}">ver empleados</a>
                            </td>
                        </tr>
                        {% endfor %}
                       
                    </tbody>
                </table>

            </div>
        </div>

    </div>
    

{% endblock contenido %}

templates/home/add.html
<h2>probabndo el crete view</h2>
<form method="POST">{% csrf_token %}

{{form.as_p}}

<button type="submit">Guardar</button>

</form>

templates/home/prueba.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/foundation.min.css'%}">
    <title>Document</title>
</head>

<body>

    <h1 class="ejemplo">que tal amigos </h1>

    <h1 class="ejemplo1">que tal BHTHERS </h1>


    <!-- Anchors (links) -->
<a href="about.html" class="button">Learn More</a>
<a href="#features" class="button">View All Features</a>

<!-- Buttons (actions) -->
<button class="submit success button">Save</button>
<button type="button" class="alert button">Delete</button>
</body>
</html>

templates/home/resumen_foundation.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel ="stylesheet" href="{% static 'css/foundation.min.css' %}">
</head>
<body>
    <h1>Resumen Foundation!!</h1>
</body>
</html>

templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Empleado</li>
        <li>
          <a href="{% url 'persona_app:listar-todo'%}">Listar</a>
    
        </li>
        <li><a href="{% url 'departamento-list'%}">Departamento</a></li>
        <li><a href="{% url 'persona_app:lista-admin'%}">Administrar</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Buscar empleado"></li>
        <li><a href="{% url 'persona_app:empleado-add'%}" class="button">Registrar Nuevo  </a></li>
      </ul>
    </div>
  </div>

templates/inicio.html
{% extends 'base.html' %}

{% load static %}


{% block titulo  %} pagina sistema de empleados {% endblock titulo %}



{% block contenido%} 

{% include 'includes/header.html'%}
<!--inicio de la la imagen de portada -->
<div class="orbit" role="region" aria-label="Favorite Space Pictures" data-orbit>
    <div class="orbit-wrapper">
      <div class="orbit-controls">
        <button class="orbit-previous"><span class="show-for-sr">Previous Slide</span>&#9664;&#xFE0E;</button>
        <button class="orbit-next"><span class="show-for-sr">Next Slide</span>&#9654;&#xFE0E;</button>
      </div>
      <ul class="orbit-container">
        <li class="is-active orbit-slide">
          <figure class="orbit-figure">
            <img class="orbit-image" src="{% static 'img/logo.jpg' %}" alt="Space">
            <figcaption class="orbit-caption">Space, the final frontier.</figcaption>
          </figure>
        </li>
        <li class="orbit-slide">
          <figure class="orbit-figure">
            <img class="orbit-image" src="{% static 'img/pizza.jpg' %}" alt="Space">
            <figcaption class="orbit-caption">Lets Rocket!</figcaption>
          </figure>
        </li>

      </ul>
    </div>

  </div>
<!--fin de la imagen de portada -->
<div class ="grid-x align-center">
    <h1 class="cell large-8" sytle="font-size: 5px; text-align:center;">Bienvenido al sistema de registro de empleado</h1>
    <div class="cell large-7">
        <div class="callout secondary">
            <h5>Registro de empleados</h5>
            <p>It has an easy to override visual style, and is appropriately subdued.
                It has an easy to override visual style, and is appropriately subdued 
            </p>
            <a href="#">ver empleados .</a>
          </div>
    </div>
</div>
<!--bloque de bienvenida-->

{% endblock contenido %}

templates/persona/add-empleado.html
{% extends 'base.html'%}
{% block titulo %} 
    Agregar empleado
{% endblock titulo%}

{% block contenido %}

{%include "includes/header.html"%}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Resgistrar empleado</h1>
        <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
            
            <div class="medium-6 cell">
                <label>Nombres:
                    {{form.first_name}} 
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellidos:
                    {{form.last_name}} 
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Trabajo:
                    {{form.job}} 
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Departamento:
                    {{form.departamento}} 
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Imagen:
                    {{form.avatar}} 
                </label>
            </div>
            <div class="medium-6 cell">
               <button type="submit" class="button success"> Guardar </button>
            </div>


        </form>

    </div>

</div>


{% endblock contenido %}

templates/persona/by_kword.html
<h1>Buscar empleados por palabra clave</h1>
<form method="GET">{% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="Ingrese nombre Aqui">
    <button type="submit">Buscar</button>
</form>

<h3>lista de resultados</h3>

<ul>
    {% for e in hola %}
        <li>{{e}}</li>
    
    {% endfor %}

</ul>

templates/persona/delete.html
{% extends 'base.html'%}
{% block titulo %} 
    eliminar empleado
{% endblock titulo%}

{% block contenido %}

{%include "includes/header.html"%}

<div class ="grid-container">
    <div class="grid-x">
        <h1>Eliminar empleado:{{object.first_name}}</h1>
    </div>

    <form class="cell" method="POST">{% csrf_token %}
        <div class="callout secondary">
            <h5>¿Desae eliminar?</h5>
        
          </div>
        <p>confirme que desea eliminar</p>
        <button type="submit" class="alert button">Confirmar </button>
       
    </form>

</div>




{% endblock contenido %}

templates/persona/detail_empleado.html
<h1>VER DETALLE DE EMPLEADOS </h1>

{{empleado}}

<h3>todos los datos</h3>
<p>{{empleado.first_name}}</p>
<p>{{empleado.last_name}}</p>
<p>{{empleado.job}}</p>
<p>{{empleado.departamento}}</p>

templates/persona/list_all.html
{%extends 'base.html'%}


{% block contenido %}

{% include "includes/header.html" %}

    <div class="grid-contanier">

        <div class="grid-x">
            <h1 class="cell">listar empleados </h1>
            <form class="cell grid-x grid-margin-x" method="GET">
                <div class="cell large-7">
                    <input type="text" id="kword" name="kword" placeholder="buscar empleado">
                </div>
                <div class ="cell large-2">
                    <button type="submit" class="submit success button"> buscar </button>
                </div>
            </form>
            <div class ="cell">
                <table>
                    <thead>
                      <tr>
                        <th width="200">ID</th>
                        <th>Nombre</th>
                        <th width="150">APELLIDOS </th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="150">ACCION</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for e in empleados %}
                      <tr>
                        <td>{{e.id}}</td>
                        <td>{{e.first_name}}</td>
                        <td>{{e.last_name}}</td>
                        <td>{{e.departamento}}</td>
                        <td>{{e.avatar}}</td>
                        <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">ver</a></td>
                      </tr>
                       {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class = "cell">
                {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                           <a href="?page={{page_obj.previous_page_number}}"> Atras </a>
                        </li>
                        {% endif %}

                        {% for pagina in paginator.page_range %}
                        
                        <li>
                            <a href="?page={{pagina}}" aria-label="Page 2">{{pagina}}</a></li>
                        {% endfor%}

                      
                        {% if page_obj.has_next %}    
                        <li class="pagination-next">
                            <a href="?page={{page_obj.next_page_number}}"> siguiente</a>
                        </li>
                        {% endif %}
                    </ul>
                  </nav>
                {% endif %}  
            </div>

        </div>
  
    </div>
{% endblock contenido %}

templates/persona/list_by_area.html
{% extends 'base.html'%}
{% block titulo %}
{% endblock titulo %}
{% block contenido%}
{% include 'includes/header.html'%}



<div class="grid-contanier">

   <div class="grid-x">
       <h1 class="cell">listar empleados por area </h1>
       
       <div class ="cell">
           <table>
               <thead>
                 <tr>
                   <th width="200">ID</th>
                   <th>Nombre</th>
                   <th width="150">APELLIDOS </th>
                   <th width="150">DEPARTAMENTO</th>
                   <th width="150">ACCION</th>
                 </tr>
               </thead>
               <tbody>
                   {% for e in empleados %}
                 <tr>
                   <td>{{e.id}}</td>
                   <td>{{e.first_name}}</td>
                   <td>{{e.last_name}}</td>
                   <td>{{e.departamento}}</td>
                   <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">ver</a></td>
                 </tr>
                  {% endfor %}
               </tbody>
           </table>
       </div>

   </div>

</div>

{% endblock contenido %}
<ul>
   {% for e in object_list %}
    <li>{{e}}</li>
   {% endfor %}
</ul>

templates/persona/list_empleados.html
<h1>hola amigosss</h1>
{%extends 'base.html'%}


{% block contenido %}

{% include "includes/header.html" %}

    <div class="grid-contanier">

        <div class="grid-x">
            <h1 class="cell">listar empleados </h1>
            
            <div class ="cell">
                <table>
                    <thead>
                      <tr>
                        <th width="200">ID</th>
                        <th>Nombre</th>
                        <th width="150">APELLIDOS </th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="150">ACCION</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for e in empleados %}
                      <tr>
                        <td>{{e.id}}</td>
                        <td>{{e.first_name}}</td>
                        <td>{{e.last_name}}</td>
                        <td>{{e.departamento}}</td>
                        <td><a class="button success" href="{% url 'persona_app:modificar_empleado' e.id %}">editar</a></td>
                        <td><a class="button alert" href="{% url 'persona_app:eliminar-empleado' e.id %}">eliminar</a></td>
                      </tr>
                       {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class = "cell">
                {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                           <a href="?page={{page_obj.previous_page_number}}"> Atras </a>
                        </li>
                        {% endif %}

                        {% for pagina in paginator.page_range %}
                        
                        <li>
                            <a href="?page={{pagina}}" aria-label="Page 2">{{pagina}}</a></li>
                        {% endfor%}

                      
                        {% if page_obj.has_next %}    
                        <li class="pagination-next">
                            <a href="?page={{page_obj.next_page_number}}"> siguiente</a>
                        </li>
                        {% endif %}
                    </ul>
                  </nav>
                {% endif %}  
            </div>

        </div>
  
    </div>
{% endblock contenido %}

templates/persona/success.html
<h1>te registrastes exisitosamente</h1>

templates/persona/update.html
{% extends 'base.html'%}
{% block titulo %} 
    Editar empleado
{% endblock titulo%}

{% block contenido %}

{%include "includes/header.html"%}
<div class="grid-container">
    <div class="grid-x">
        <h1 class ="cell">
            Modificar Empleado
        </h1>
        <div class="cell">
            <form class="grid-x grid-margin-x" method="POST">{% csrf_token %}
                <div class=" cell large-6">
                    <label>Nombres:
                      {{form.first_name}}
                    </label>
                </div>
              
                <div class=" cell large-6">
                    <label>Apellidos:
                      {{form.last_name}}
                    </label>
                </div>
                <div class=" cell large-6">
                    <label>Trabajo:
                      {{form.job}}
                    </label>
                </div>
                <div class=" cell large-6">
                    <label>Departamento:
                      {{form.departamento}}
                    </label>
                </div>
                <div class=" cell large-6">
                    <button type="submit" class="submit success button">Actualizar </button>
                </div>
                
            
            </form>
            

        </div>

    </div>



</div>



{% endblock contenido %}